### ISSUE TITLE
Warning: Unable to fetch subsection parameters! Addressing subsection parameters will not work for this tool.

### ISSUE THREAD

**Issue by yvhkgdsk0** [userbz/DeMix#2]
Hi,

I am trying to use Demix, there is an error message showed:
 "00:08:27 NOTICE: GenericWrapper (DeMix) of node #8 started. Processing ...
Warning: Unable to fetch subsection parameters! Addressing subsection parameters will not work for this tool."

I don't know what is really going wrong, please help me.

I can't attach the log file at here, would you give me a email address that I can send you the log file?

Thank you!

Qi

**Comment by userbz** [comment]
Hi Qi,

It is a normal warning for External Tools. 
Just ignore it if you can get any MGF output from the node after all. 

Best regards,

**Comment by yvhkgdsk0** [comment]
Hi,

I didn't get any MGF output. It stopped at the second MSGFPlusAdapter. It is seems that the Demix part didn't create the right output. The 009-GenericWrapper-EToolout direction just contained a zero size file.

 Any other reasons?

Best regards,
Qi

**Comment by userbz** [comment]
I seems the python script for MS/MS cloning didn't work. Would you mind manually execute the python script "ms2_clone" under command line?

**Comment by userbz** [comment]
One bug I found earlier was that, when the mzML file path contains a space char in it, the script might fail to parse the file name. However, when the feature list, mzID and mzML files are ready, the best way is still to manually check if the Python script works under command line. Basically, the DeMix TOPP node is just an automation of doing so.

**Comment by yvhkgdsk0** [comment]
Thank you!

Follow your instructions, I tried manually execute the python script "feature_ms2_clone_TOPP2.py" under command line and got an empty mgf file, but the input .mzid, .featureXML are not empty.
Here are my command and output:
python feature_ms2_clone_TOPP2.py -feature ../20160208/TOPPAS_out/006-FeatureFinderCentroided-out/Hela_Spike_1h.featureXML -psm ../20160208/TOPPAS_out/003-MSGFPlusAdapter-mzid_out/Hela_Spike_1h.mzid -w 2 -out_dir ../ ../../Hela_Spike_1h.mzML 
feature_ms2_clone_TOPP2.py -feature ../20160208/TOPPAS_out/006-FeatureFinderCentroided-out/Hela_Spike_1h.featureXML -psm ../20160208/TOPPAS_out/003-MSGFPlusAdapter-mzid_out/Hela_Spike_1h.mzid -w 2 -out_dir ../ ../../Hela_Spike_1h.mzML
Mean precursor mass error (ppm): 0.303 SD: 2.580
Auto correct precursor m/z offset: 0.30 ppm 
DeMix 1000 MS/MS (~3.6%)
DeMix 2000 MS/MS (~7.1%)
DeMix 3000 MS/MS (~10.7%)
DeMix 4000 MS/MS (~14.3%)
DeMix 5000 MS/MS (~17.8%)
DeMix 6000 MS/MS (~21.4%)
DeMix 7000 MS/MS (~25.0%)
DeMix 8000 MS/MS (~28.6%)
DeMix 9000 MS/MS (~32.1%)
DeMix 10000 MS/MS (~35.7%)
DeMix 11000 MS/MS (~39.3%)
DeMix 12000 MS/MS (~42.8%)
DeMix 13000 MS/MS (~46.4%)
DeMix 14000 MS/MS (~50.0%)
DeMix 15000 MS/MS (~53.5%)
DeMix 16000 MS/MS (~57.1%)
DeMix 17000 MS/MS (~60.7%)
DeMix 18000 MS/MS (~64.2%)
DeMix 19000 MS/MS (~67.8%)
DeMix 20000 MS/MS (~71.4%)
DeMix 21000 MS/MS (~74.9%)
DeMix 22000 MS/MS (~78.5%)
DeMix 23000 MS/MS (~82.1%)
DeMix 24000 MS/MS (~85.7%)
DeMix 25000 MS/MS (~89.2%)
DeMix 26000 MS/MS (~92.8%)
DeMix 27000 MS/MS (~96.4%)
DeMix 28000 MS/MS (~99.9%)

Does anything unusual?

**Comment by userbz** [comment]
Oh, I saw you put the featureXML as the input, which should be replaced by the exported CSV file. For simplicity, I wrote the python script to read text rather than the XML.

**Comment by yvhkgdsk0** [comment]
Here is the new command:
python feature_ms2_clone_TOPP2.py -feature ../20160208/TOPPAS_out/012-TextExporter-out/Hela_Spike_1h.csv -psm ../20160208/TOPPAS_out/003-MSGFPlusAdapter-mzid_out/Hela_Spike_1h.mzid -w 2 -out_dir ../ ../../Hela_Spike_1h.mzML
The output mgf file still empty.

**Comment by userbz** [comment]
Well, would you mind share the files to me, via dropbox or so?

**Comment by userbz** [comment]
It looks quite wired to me, because even if no feature matched DeMix will still generate a set of spectra the same as input. Otherwise, there must be a problem with reading the mzML file.

**Comment by yvhkgdsk0** [comment]
Great!

Here is very slow to upload files throuth dropbox. It is about 100 MB, I can sent to you just through my 163 email(yvhkgdsktq@163.com) or Baidu SkyDrive. Please tell me which way is better?.

Maybe I can try the old command way instead the newest way which based on OpenMS. 

Thank you very much!

**Comment by userbz** [comment]
Baidu is fine to me, 163 is slow here.

The old pipeline is essentially the same as the current one, because I did not change much in the process. However, if you wish to do some debugging, you can check if the script reads your mzML properly. 
i.e. after line 83:  if spec['ms level'] == 2.0 
and line 103   for p in spec['precursors']:

**Comment by yvhkgdsk0** [comment]
Here is the link: (http://pan.baidu.com/s/1o6YPI8U; Code:rjqg)

I would like to do some debugging, I will let you know what i get.

**Comment by userbz** [comment]
Hi Qi,

I found the problem is in parsing the XML for retention time! 
My script look for the tag "scan time", however, it is coded as "scan start time" in you mzML. I am updating the script for this compatibility issue. 

Thank you for the feedback and happy new year!
