### ISSUE TITLE
Rescoring Step

### ISSUE THREAD

**Issue by naimrashid** [userbz/DeMix#3]
I have read through your TOPPAS code and was wondering at what step the PSM rescoring (as described in the DEMIX publication) is taking place.  The TOPPAS code also uses MSGF-plus, and it is not clear how any filtering is being done post-second pass search.  Is this rescoring still relevant as it is discussed in the publication, or do we now use the scoring based on the MSGF plus scores for filtering?

We also had some problems trying to find the IDpicker software to identify and filter protein groups from our output, and instead used peptide/protein prophet (semiparametric model using decoys).  Would this be appropriate in your experience?  Thank you very much for your help

**Comment by userbz** [comment]
Hi, naimrashid.

I have to say that the post-processing of re-scoring PSMs was done only with Morpheus, which can hardly be integrated in OpenMS and used as cross-platform. The algorithm of re-scoring has been moved to the path of deprecated/Version_0/post2_psmRescore.py

However, MSGF-plus is claimed to be a "universal" search engine that handles not only high-resolution HCD spectra, but also various other types, which I think could make the identification process a bit easier to users, and PSM re-scoring could still be done with tools like Percolator. 

I also have some difficulty with updating IDpicker. It seems the authors are no longer supporting it, I am not sure. If so, it would be very sad for losing such a handy tool. I think your approach with ProteinProphet is definitely all right. 

Thank you for the comment and sorry for my late reply.
Best regards,

**Comment by userbz** [comment]
IDPicker now appears to be a part of the ProteoWizard.
